/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author kevinjimenez
 */
public class FrmEntradas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEntradas.class.getName());

    /**
     * Creates new form FrmEntradas
     */
    public FrmEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblServicioPrincipal = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblHoraEntrada = new javax.swing.JLabel();
        lblServiciosAdicionales = new javax.swing.JLabel();
        lblCostoTotal = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        cmbVehiculo = new javax.swing.JComboBox<>();
        cmbServicio = new javax.swing.JComboBox<>();
        dcFechaIngreso = new com.toedter.calendar.JDateChooser();
        chkAspirado = new javax.swing.JCheckBox();
        chkAromatizante = new javax.swing.JCheckBox();
        chkEncerado = new javax.swing.JCheckBox();
        chkPulido = new javax.swing.JCheckBox();
        txtCostoTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnCalcular = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtHoraEntrada = new javax.swing.JTextField();
        lblHoraSalida = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Entrada Vehículos");

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTitulo.setText("ENTRADA DE VEHÍCULOS");

        lblCliente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCliente.setText("Cliente:");

        lblVehiculo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblVehiculo.setText("Vehículo:");

        lblServicioPrincipal.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblServicioPrincipal.setText("Servicio Principal:");

        lblFechaIngreso.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblFechaIngreso.setText("Fecha Ingreso:");

        lblHoraEntrada.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHoraEntrada.setText("Hora Entrada:");

        lblServiciosAdicionales.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblServiciosAdicionales.setText("Servicios Adicionales:");

        lblCostoTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCostoTotal.setText("Costo Total:");

        lblObservaciones.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblObservaciones.setText("Observaciones:");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cliente 1", "Cliente 2", "Cliente 3" }));

        cmbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona uno", "Vehículo 1", "Vehículo 2", "Vehículo 3" }));

        cmbServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Lavado Exterior", "Lavado Completo", "Pulido", "Encerado", "Detallado" }));

        chkAspirado.setText("Aspirado (+$20)");

        chkAromatizante.setText("Aromatizante (+$15)");

        chkEncerado.setText("Encerado (+$50)");

        chkPulido.setText("Pulido (+$100)");

        txtCostoTotal.setEnabled(false);

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        btnCalcular.setBackground(new java.awt.Color(0, 255, 204));
        btnCalcular.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(0, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnGuardar.setText("Guardar");

        btnRegresar.setBackground(new java.awt.Color(0, 255, 204));
        btnRegresar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        txtHoraEntrada.setText("-----");

        lblHoraSalida.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHoraSalida.setText("Hora Salida:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblServicioPrincipal)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblObservaciones)
                            .addComponent(btnRegresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCliente)
                            .addComponent(lblVehiculo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServiciosAdicionales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkEncerado)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkPulido))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkAspirado)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkAromatizante))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCostoTotal)
                                .addGap(34, 34, 34)
                                .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFechaIngreso)
                                            .addComponent(lblHoraEntrada))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtHoraEntrada)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblHoraSalida)
                                            .addComponent(lblTitulo))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblServiciosAdicionales)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCalcular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehiculo)
                            .addComponent(cmbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServicioPrincipal)
                            .addComponent(cmbServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaIngreso)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHoraEntrada)
                            .addComponent(txtHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraSalida)
                            .addComponent(txtHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkAspirado)
                            .addComponent(chkAromatizante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkEncerado)
                            .addComponent(chkPulido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCostoTotal))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblObservaciones)
                        .addGap(26, 26, 26)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double total = 0;
        // Servicio principal
        String servicio = cmbServicio.getSelectedItem().toString();
        switch(servicio){

    case "Lavado Exterior":
        total += 80;
        break;

    case "Lavado Completo":
        total += 150;
        break;

    case "Pulido":
        total += 350;
        break;

    case "Encerado":
        total += 200;
        break;

    case "Detallado":
        total += 500;
        break;
}
        // Servicios adicionales
        if(chkAspirado.isSelected())
    total += 20;

if(chkAromatizante.isSelected())
    total += 15;

if(chkEncerado.isSelected())
    total += 50;

if(chkPulido.isSelected())
    total += 100;
// Mostrar total
txtCostoTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEntradas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chkAromatizante;
    private javax.swing.JCheckBox chkAspirado;
    private javax.swing.JCheckBox chkEncerado;
    private javax.swing.JCheckBox chkPulido;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbServicio;
    private javax.swing.JComboBox<String> cmbVehiculo;
    private com.toedter.calendar.JDateChooser dcFechaIngreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblServicioPrincipal;
    private javax.swing.JLabel lblServiciosAdicionales;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtHoraEntrada;
    private javax.swing.JTextField txtHoraSalida;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
